### PR TITLE
Adds Dockerfile and docker-compose.yml

### PR DESCRIPTION
**Pull request by prologic**
This sucessfully "Dockerizes" this neat little app.

``` #!bash
$ docker images | grep leselys
leselys_leselysserver       latest              e245300a465d        18 minutes ago      241.7 MB
leselys_leselysworker       latest              e245300a465d        18 minutes ago      241.7 MB
```

Tested with [autodock-paas](https://github.com/prologic/autodock-paas)
and [Docker](https://www.docker.com) 1.9+

### CODE REVIEW

**Comment by socketubs** [comment]
Hi @prologic ,

Thank you for your work! :smile: 
Can you add a little note un readme about "_How to deploy with Docker_"?
(Do not hesitate to remove broken links by the way).

**Comment by prologic** [comment]
Yes ofc :) It's late though; I'll do it tomorrow and fix the broken screenshots too :)

**Comment by prologic** [comment]
Done! You can see the updated results [here](https://github.com/prologic/leselys/tree/dockerize) including the screenshots that I also fixed and added to the repo. If you're happy with this I just have to make one final edit and amend to make the URI(s) of the screenshots point to your repo :)

**Comment by socketubs** [comment]
Perfect! :smile: 
Ping me when it's done to be merge.

**Comment by prologic** [comment]
Done!

**Comment by prologic** [comment]
:+1:  :)

**Comment by socketubs** [comment]
Thank you!
Do not hesitate if you have any idea/cleanup for Leselys. :smiley:

**Comment by prologic** [comment]
I have a few I'd love to "steal" from CommaFeed:

- Tree view with unread counts and auto hide (on 0 unread)
- Show titles only; let the user selectively decide what to actually read!
- Improve UI buttons; move to center; move obvious (larger?)

**Pull request merged**
